### ISSUE TITLE
0.0.6 Milestone

### ISSUE THREAD

**Issue by shimamoto** [bizreach/aws-kinesis-scala#12]
We are working following towards the 0.0.6 release:

- [x] Upgrade aws-java-sdk to 1.11.119+
- [x] Support `RequestMetricCollector` per request
- [x] Support Kinesis Firehose
- [x] Enhance AsyncClient support

**Comment by damianbl** [comment]
Do you need any help with those two remaining features?

**Comment by shimamoto** [comment]
Thank you but I’m good.
I am working on the v0.0.6 branch. Only one feature left. I send PR when it's done and have another member review it.

Probably we will release version 0.0.6 by the end of this month :)

**Comment by damianbl** [comment]
Cool. :)
